# Generated by Django 5.0.3 on 2024-03-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='photo',
            field=models.ImageField(upload_to='img/folder/'),
        ),
    ]
